In [2]:
import pandas as pd
import numpy as np

---
# 안다르 자사몰 리뷰 데이터

## 1. 전처리

In [3]:
# 안다르
df_review_andar_D2C = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/andar_reviews_final_new.csv")
display(df_review_andar_D2C.head(3))
display(df_review_andar_D2C.info())

,review_id,product_id,post_date,post_time,platform,brand,search_keyword,content,source_url,rating,...,media_count,main_content_type,upload_from,labels,topics,키,몸무게,평소사이즈,사이즈_평가,사이즈_한줄평
0,48724074,5147,2026-04-14,03:48:43,자사몰리뷰,안다르,릴렉스 마사지 듀얼볼 Ⅱ,"러닝 후 몸 풀어주는 용으로 아주 좋아요. 종아리나 등, 목 뒤에 사용하기 좋아요....",https://andar.co.kr/product/detail.html?produc...,5,...,2,image,vreview-board,[],"['functionality', 'activity', 'color']",155~159cm,45~49kg,S,잘 맞아요,마사지하기 딱 좋은 사이즈!
1,48590531,5147,2026-04-07,17:50:41,네이버페이,안다르,릴렉스 마사지 듀얼볼 Ⅱ,딱딱하네요\n저는 말랑말랑 한줄 알았어요(2026-04-07 20:15:59 에 등...,https://andar.co.kr/product/detail.html?produc...,3,...,0,text,api-ingest,[],['material'],NaN,NaN,NaN,NaN,NaN
2,48535840,5147,2026-04-05,10:10:20,자사몰리뷰,안다르,릴렉스 마사지 듀얼볼 Ⅱ,요가링이랑 폼롤러랑 같이 사서 집에서 잘 굴려주고 있어요 색깔도 너무 예쁘고 귀여워...,https://andar.co.kr/product/detail.html?produc...,5,...,1,image,vreview-board,['재구매'],"['activity', 'color']",165~169cm,55~59kg,M,잘 맞아요,좋아요

<class 'pandas.DataFrame'>
RangeIndex: 925663 entries, 0 to 925662
Data columns (total 26 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   review_id          925663 non-null  int64
 1   product_id         925663 non-null  int64
 2   post_date          925663 non-null  str
 3   post_time          925663 non-null  str
 4   platform           925663 non-null  str
 5   brand              925663 non-null  str
 6   search_keyword     925663 non-null  str
 7   content            918763 non-null  str
 8   source_url         925663 non-null  str
 9   rating             925663 non-null  int64
 10  helpful_count      925663 non-null  int64
 11  purchased_option   750889 non-null  str
 12  has_image          925663 non-null  int64
 13  collect_date       925663 non-null  str
 14  title              676233 non-null  str
 15  user_nickname      925663 non-null  str
 16  media_count        925663 non-null  int64
 17  main_content_type  925663 non-null  str
 18  upload_from        925663 non-null  str
 19  labels             925663 non-null  str
 20  topics             925663 non-null  str
 21  키                  633734 non-null  str
 22  몸무게                624861 non-null  str
 23  평소사이즈              620967 non-null  str
 24  사이즈_평가             677892 non-null  str
 25  사이즈_한줄평            654363 non-null  str
dtypes: int64(6), str(20)
memory usage: 630.4 MB

None

In [4]:
# =======================================
# 사용할 컬럼만 선택
# =======================================
df_review_andar_D2C = df_review_andar_D2C.drop(['post_time', 'brand', 'user_nickname', 'media_count', 'main_content_type', 'upload_from', 'labels', 'topics', '평소사이즈', '사이즈_평가'], axis=1)
df_review_andar_D2C.head(3)

,review_id,product_id,post_date,platform,search_keyword,content,source_url,rating,helpful_count,purchased_option,has_image,collect_date,title,키,몸무게,사이즈_한줄평
0,48724074,5147,2026-04-14,자사몰리뷰,릴렉스 마사지 듀얼볼 Ⅱ,"러닝 후 몸 풀어주는 용으로 아주 좋아요. 종아리나 등, 목 뒤에 사용하기 좋아요....",https://andar.co.kr/product/detail.html?produc...,5,0,"[EJFMB-02DPK] 샤이 핑크, F (Free)",1,2026-04-21,릴렉스 마사지 듀얼볼 Ⅱ 후기,155~159cm,45~49kg,마사지하기 딱 좋은 사이즈!
1,48590531,5147,2026-04-07,네이버페이,릴렉스 마사지 듀얼볼 Ⅱ,딱딱하네요\n저는 말랑말랑 한줄 알았어요(2026-04-07 20:15:59 에 등...,https://andar.co.kr/product/detail.html?produc...,3,0,NaN,0,2026-04-21,보통,NaN,NaN,NaN
2,48535840,5147,2026-04-05,자사몰리뷰,릴렉스 마사지 듀얼볼 Ⅱ,요가링이랑 폼롤러랑 같이 사서 집에서 잘 굴려주고 있어요 색깔도 너무 예쁘고 귀여워...,https://andar.co.kr/product/detail.html?produc...,5,0,"[EJFMB-02DPK] 샤이 핑크, F (Free)",1,2026-04-21,릴렉스 마사지 듀얼볼 Ⅱ 후기,165~169cm,55~59kg,좋아요

In [ ]:
# =======================================
# 리뷰 본문 합치기 => content + title, 사이즈_한줄평
# =======================================
# 합치기
df_review_andar_D2C['content'] = df_review_andar_D2C[['content', 'title', '사이즈_한줄평']].fillna('').agg(' '.join, axis=1).str.strip()

# 합친 컬럼 삭제하기
df_review_andar_D2C = df_review_andar_D2C.drop(['title', '사이즈_한줄평'], axis=1)

display(df_review_andar_D2C.head())

,review_id,product_id,post_date,platform,search_keyword,content,source_url,rating,helpful_count,purchased_option,has_image,collect_date,키,몸무게
0,48724074,5147,2026-04-14,자사몰리뷰,릴렉스 마사지 듀얼볼 Ⅱ,"러닝 후 몸 풀어주는 용으로 아주 좋아요. 종아리나 등, 목 뒤에 사용하기 좋아요....",https://andar.co.kr/product/detail.html?produc...,5,0,"[EJFMB-02DPK] 샤이 핑크, F (Free)",1,2026-04-21,155~159cm,45~49kg
1,48590531,5147,2026-04-07,네이버페이,릴렉스 마사지 듀얼볼 Ⅱ,딱딱하네요\n저는 말랑말랑 한줄 알았어요(2026-04-07 20:15:59 에 등...,https://andar.co.kr/product/detail.html?produc...,3,0,NaN,0,2026-04-21,NaN,NaN
2,48535840,5147,2026-04-05,자사몰리뷰,릴렉스 마사지 듀얼볼 Ⅱ,요가링이랑 폼롤러랑 같이 사서 집에서 잘 굴려주고 있어요 색깔도 너무 예쁘고 귀여워...,https://andar.co.kr/product/detail.html?produc...,5,0,"[EJFMB-02DPK] 샤이 핑크, F (Free)",1,2026-04-21,165~169cm,55~59kg
3,48535469,5147,2026-04-05,자사몰리뷰,릴렉스 마사지 듀얼볼 Ⅱ,묵직하니 사용하기 편하네요 릴렉스 마사지 듀얼볼 Ⅱ 후기 정사이즈,https://andar.co.kr/product/detail.html?produc...,5,0,"[EJFMB-02DPK] 샤이 핑크, F (Free)",0,2026-04-21,160~164cm,50~54kg
4,48521693,5147,2026-04-03,자사몰리뷰,릴렉스 마사지 듀얼볼 Ⅱ,시원하게 마사지가되요 여기저기 쉽게 문지르고 아픈 부위 꾹꾹 눌러주니 시원하네요 릴...,https://andar.co.kr/product/detail.html?produc...,5,0,"[EJFMB-02DPK] 샤이 핑크, F (Free)",1,2026-04-21,160~164cm,55~59kg

In [11]:
display(df_review_andar_D2C.info())

<class 'pandas.DataFrame'>
RangeIndex: 925663 entries, 0 to 925662
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   review_id         925663 non-null  int64
 1   product_id        925663 non-null  int64
 2   post_date         925663 non-null  str
 3   platform          925663 non-null  str
 4   search_keyword    925663 non-null  str
 5   content           925663 non-null  str
 6   source_url        925663 non-null  str
 7   rating            925663 non-null  int64
 8   helpful_count     925663 non-null  int64
 9   purchased_option  750889 non-null  str
 10  has_image         925663 non-null  int64
 11  collect_date      925663 non-null  str
 12  키                 633734 non-null  str
 13  몸무게               624861 non-null  str
dtypes: int64(5), str(9)
memory usage: 477.4 MB

None

In [ ]:
df_review_andar_D2C['키'].isna().mean()*100

In [17]:
# =======================================
# review_id 중복 확인
# =======================================
df_review_andar_D2C['review_id'].duplicated().sum()

np.int64(0)

In [ ]:
# =======================================
# 결측치 처리
# =======================================
# purchased_option => 18.8%
# 키 => 31.5%
# 몸무게 => 32.4%

np.float64(32.49584351972586)

In [ ]:
# purchased_option => 18.8%
pd.set_option('display.max_colwidth', None) # 컬럼 안 텍스트 잘림 제거
df_review_andar_D2C[['search_keyword', 'source_url', 'purchased_option']].drop_duplicates().head(20)
# ‘product_id’와 제품 옵션이 1:1로 매칭되지 않음. 결측치 그대로 유지

,search_keyword,source_url,purchased_option
0,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02DPK] 샤이 핑크, F (Free)"
1,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,NaN
6,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02NAV] 마린 네이비, F (Free)"
28,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02PNK] 블라썸핑크, F (Free)"
58,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02MNT] 파스텔민트, F (Free)"
75,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02BLU] 마일드 블루, F (Free)"
313,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02BLK] 블랙, F (Free)"
314,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02GRN] 포레스트 그린, F (Free)"
976,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02GRY] 올리브그레이, F (Free)"
1429,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJPMB-07CRM] 치즈크림, F (Free)"
1462,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJPMB-07GRY] 올리브그레이, F (Free)"
1564,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJPMB-07PNK] 블라썸핑크, F (Free)"
1766,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02LVD] 페털 라일락, F (Free)"
1964,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJPMB-07MNT] 파스텔민트, F (Free)"
2355,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02BLK] 시크 블랙, F (Free)"
2506,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EKRMB-02LVD] 페털 라일락, F (Free)"
4115,요가매트 스트랩 위드,https://andar.co.kr/product/detail.html?product_no=5361,"[EJSST-01GRN] 아카시아그린, F (Free)"
4117,요가매트 스트랩 위드,https://andar.co.kr/product/detail.html?product_no=5361,NaN
4121,요가매트 스트랩 위드,https://andar.co.kr/product/detail.html?product_no=5361,"[EJSST-01DGY] 프로스트그레이, F (Free)"
4123,요가매트 스트랩 위드,https://andar.co.kr/product/detail.html?product_no=5361,"[EJSST-01BLK] 블랙, F (Free)"

In [ ]:
# 키 => 31.5%
df_review_andar_D2C['키'] = df_review_andar_D2C['키'].astype(object)
df_review_andar_D2C['키'] = df_review_andar_D2C['키'].fillna(None) # None으로 잘 대체 됨.

# 몸무게 => 32.4%
df_review_andar_D2C['몸무게'] = df_review_andar_D2C['몸무게'].astype(object)
df_review_andar_D2C['몸무게'] = df_review_andar_D2C['몸무게'].fillna(None) # None으로 잘 대체 됨.

# display(df_review_andar_D2C['키'].value_counts(dropna=False))
# display(df_review_andar_D2C['몸무게'].value_counts(dropna=False))

In [ ]:
# =======================================
# 파생컬럼 생성 (year, month)
# =======================================
df_review_andar_D2C['post_date'] = pd.to_datetime(df_review_andar_D2C['post_date'])
df_review_andar_D2C['post_date'].value_counts()

In [ ]:
# =======================================
# 컬럼 이름 통일
# =======================================

# search_keyword => product_name으로 변경해야 함.

In [ ]:
# =======================================
# 없는 컬럼 추가
# =======================================

In [ ]:
# =======================================
# 데이터 타입 통일
# =======================================

In [ ]:
# =======================================
# 저장
# =======================================

---
# 안다르 무신사 리뷰 데이터

## 1. 전처리

In [48]:
df_review_andar_mss = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/musinsa_andar_reviews.csv", encoding='utf-8')
display(df_review_andar_mss.head())
display(df_review_andar_mss.info())

,collect_date,review_date,product_id,product_name,review_no,review_type,rating,review_text,author,user_height,user_weight,option,helpful,comment_count,has_image,image_urls,survey_json,url
0,2026-04-21 23:09:37,2024-07-09,3297519,릴렉스 에어소프트 요가매트 (8mm),62257472,스타일,5,색깔이 그레이에 초록 한스푼 넣은 느낌이에요 디자인이 깔끔해서 너무 맘에 듭니다 두...,Whg_,0,0,F · 포그 그레이[EJFMT-01LGY],0,0,True,https://www.musinsa.com/data/estimate/3297519_...,NaN,https://www.musinsa.com/products/3297519#revie...
1,2026-04-21 23:09:37,2024-06-25,3297519,릴렉스 에어소프트 요가매트 (8mm),61262848,스타일,5,뭔가 바닥 매트 같은 소재여서 로고나 디자인은 예쁘나 조금 아쉽.. 뻐덩뻐덩 한 느...,엔나짱,0,0,F · 포그 그레이[EJFMT-01LGY],0,0,True,https://www.musinsa.com/data/estimate/3297519_...,NaN,https://www.musinsa.com/products/3297519#revie...
2,2026-04-21 23:09:37,2024-05-15,3297519,릴렉스 에어소프트 요가매트 (8mm),59417236,스타일,5,안다르 매트 너무 부드럽고 색감도 이뻐요 재질 좋은거쓰시는듯,183_80,0,0,F · 포레스트 그린[EJFMT-01GRN],0,0,True,https://www.musinsa.com/data/estimate/3297519_...,NaN,https://www.musinsa.com/products/3297519#revie...
3,2026-04-21 23:09:37,2024-05-15,3297519,릴렉스 에어소프트 요가매트 (8mm),59408897,스타일,5,"아침에 스트레칭 하거나 아이가 닌텐도 링핏 할때도 사용하는데 완전 좋아요,,,",애너벨리33,0,0,F · 포그 그레이[EJFMT-01LGY],1,0,True,https://www.musinsa.com/data/estimate/3297519_...,NaN,https://www.musinsa.com/products/3297519#revie...
4,2026-04-21 23:09:37,2024-04-19,3297519,릴렉스 에어소프트 요가매트 (8mm),58192969,스타일,5,아기가 따라 운동 하고 폭싱 폭싱 하니까 점프 점프 하고 놀아요 ㅎㅎ,Bajga,0,0,F · 파스텔 민트[EJFMT-01MNT],22,0,True,https://www.musinsa.com/data/estimate/3297519_...,NaN,https://www.musinsa.com/products/3297519#revie...

<class 'pandas.DataFrame'>
RangeIndex: 7552 entries, 0 to 7551
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   collect_date   7552 non-null   str
 1   review_date    7552 non-null   str
 2   product_id     7552 non-null   int64
 3   product_name   7552 non-null   str
 4   review_no      7552 non-null   int64
 5   review_type    7552 non-null   str
 6   rating         7552 non-null   int64
 7   review_text    7552 non-null   str
 8   author         7552 non-null   str
 9   user_height    7552 non-null   int64
 10  user_weight    7552 non-null   int64
 11  option         7546 non-null   str
 12  helpful        7552 non-null   int64
 13  comment_count  7552 non-null   int64
 14  has_image      7552 non-null   bool
 15  image_urls     3007 non-null   str
 16  survey_json    1 non-null      str
 17  url            7552 non-null   str
dtypes: bool(1), int64(7), str(10)
memory usage: 3.5 MB

None