In [1]:
# 데이터 처리 및 분석
import pandas as pd
import ast
import numpy as np
from datetime import datetime, timedelta
import warnings
import re

# 시각화
import matplotlib.pyplot as plt
import seaborn as sns

# 통계 분석
from scipy import stats
from scipy.stats import shapiro, levene, ttest_ind, chi2_contingency, f_oneway
from scipy.stats import mannwhitneyu, fisher_exact, kruskal
import scikit_posthocs as sp
from statsmodels.stats.multicomp import pairwise_tukeyhsd, MultiComparison
import pingouin as pg
import platform

# ── 한글 폰트 설정 ──
if platform.system() == 'Windows':
    plt.rcParams['font.family'] = 'Malgun Gothic'
elif platform.system() == 'Darwin':
    plt.rcParams['font.family'] = 'AppleGothic'
else:
    plt.rcParams['font.family'] = 'NanumGothic'

# ── 출력 설정 ──
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
np.random.seed(42)

# 시드 설정
np.random.seed(42)

print("="*60)
print("라이브러리 로드 완료!")
print("한글 폰트 설정 완료!")
print("=" * 60)

============================================================
라이브러리 로드 완료!
한글 폰트 설정 완료!
============================================================

In [2]:
path = "/Users/wonwoo_mac/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/송원우/final_data/"

df = pd.read_csv(path + '젝시믹스_master.csv')
df.head()

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,helpful_count,has_image,purchase_option,purchase_option_color,purchase_option_size,women_size_yn,user_height,user_weight,user_height_group,user_weight_group,product_url,brand,cat1,cat2,cat3,gender,original_price,discount_price,color_count,is_new,is_best
0,2026-04-20,자사몰,5032253.0,2070608,UV 쉴드 에어핏 페이스 마스크,2026-03-09,2026,3,친구 소개로 구매했어요 친구가 걷기운동할때 필요해서 이것저것 구매했는데 기장 편하게...,5,1,1,색상:화이트 / 사이즈:L,화이트,L,0,158.0,50.0,155~159cm,50~54kg,https://www.xexymix.com/shop/shopdetail.html?b...,젝시믹스,용품,기타,골프,기타,19000.0,19000.0,3.0,False,True
1,2026-04-20,자사몰,4998316.0,2070608,UV 쉴드 에어핏 페이스 마스크,2026-01-26,2026,1,l사이즈 사고 원단도 좋고 운동시 호흡도 편한데 큰 느낌이라 작은사이즈 다시 주문했...,5,0,1,색상:블랙 / 사이즈:S/M,블랙,S/M,0,168.0,55.0,165~169cm,55~59kg,https://www.xexymix.com/shop/shopdetail.html?b...,젝시믹스,용품,기타,골프,기타,19000.0,19000.0,3.0,False,True
2,2026-04-20,자사몰,4936161.0,2070608,UV 쉴드 에어핏 페이스 마스크,2025-12-14,2025,12,구매하여 처음 사용해봤는데 가성비 진짜 좋네요 바람도 잘 막아주고 추운날씨에도 딱 ...,5,0,1,색상:블랙 / 사이즈:L,블랙,L,0,179.0,70.0,180~184cm,70~74kg,https://www.xexymix.com/shop/shopdetail.html?b...,젝시믹스,용품,기타,골프,기타,19000.0,19000.0,3.0,False,True
3,2026-04-20,자사몰,4727267.0,2070608,UV 쉴드 에어핏 페이스 마스크,2025-07-22,2025,7,전부터 풀페이스마스크 하나 사려고 보고 있다가 지난번 블랙색상 사고 마음에 들어서 ...,5,4,1,색상:화이트 / 사이즈:L,화이트,L,0,170.0,60.0,170~174cm,60~64kg,https://www.xexymix.com/shop/shopdetail.html?b...,젝시믹스,용품,기타,골프,기타,19000.0,19000.0,3.0,False,True
4,2026-04-20,자사몰,4821424.0,2070608,UV 쉴드 에어핏 페이스 마스크,2025-10-10,2025,10,낮에 러닝하는데 얼굴 타는게 신경쓰였는데 마스크 답답하지 않고 흘러 내리지 않아 좋아요,5,1,1,색상:화이트 / 사이즈:S/M,화이트,S/M,0,153.0,45.0,150~154cm,45~49kg,https://www.xexymix.com/shop/shopdetail.html?b...,젝시믹스,용품,기타,골프,기타,19000.0,19000.0,3.0,False,True

In [3]:
df_check = df[['review_id', 'review_date', 'product_name', 'year', 'month', 'rating', 'helpful_count', 'has_image', 'cat1', 'cat2', 'brand']].copy()
df_check.head()

,review_id,review_date,product_name,year,month,rating,helpful_count,has_image,cat1,cat2,brand
0,5032253.0,2026-03-09,UV 쉴드 에어핏 페이스 마스크,2026,3,5,1,1,용품,기타,젝시믹스
1,4998316.0,2026-01-26,UV 쉴드 에어핏 페이스 마스크,2026,1,5,0,1,용품,기타,젝시믹스
2,4936161.0,2025-12-14,UV 쉴드 에어핏 페이스 마스크,2025,12,5,0,1,용품,기타,젝시믹스
3,4727267.0,2025-07-22,UV 쉴드 에어핏 페이스 마스크,2025,7,5,4,1,용품,기타,젝시믹스
4,4821424.0,2025-10-10,UV 쉴드 에어핏 페이스 마스크,2025,10,5,1,1,용품,기타,젝시믹스

In [4]:
df_check.info()

<class 'pandas.DataFrame'>
RangeIndex: 501893 entries, 0 to 501892
Data columns (total 11 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   review_id      501893 non-null  float64
 1   review_date    501893 non-null  str
 2   product_name   501893 non-null  str
 3   year           501893 non-null  int64
 4   month          501893 non-null  int64
 5   rating         501893 non-null  int64
 6   helpful_count  501893 non-null  int64
 7   has_image      501893 non-null  int64
 8   cat1           501893 non-null  str
 9   cat2           501893 non-null  str
 10  brand          501893 non-null  str
dtypes: float64(1), int64(5), str(5)
memory usage: 81.7 MB

In [6]:
df_check[['brand', 'has_image']].head()

  brand  has_image
0  젝시믹스          1
1  젝시믹스          1
2  젝시믹스          1
3  젝시믹스          1
4  젝시믹스          1