In [1]:
# 데이터 처리 및 분석
import pandas as pd
import ast
import numpy as np
from datetime import datetime, timedelta
import warnings
import re

# 시각화
import matplotlib.pyplot as plt
import seaborn as sns

# 통계 분석
from scipy import stats
from scipy.stats import shapiro, levene, ttest_ind, chi2_contingency, f_oneway
from scipy.stats import mannwhitneyu, fisher_exact, kruskal
import scikit_posthocs as sp
from statsmodels.stats.multicomp import pairwise_tukeyhsd, MultiComparison
import pingouin as pg
import platform

# ── 한글 폰트 설정 ──
if platform.system() == 'Windows':
    plt.rcParams['font.family'] = 'Malgun Gothic'
elif platform.system() == 'Darwin':
    plt.rcParams['font.family'] = 'AppleGothic'
else:
    plt.rcParams['font.family'] = 'NanumGothic'

# ── 출력 설정 ──
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
np.random.seed(42)

# 시드 설정
np.random.seed(42)

print("="*60)
print("라이브러리 로드 완료!")
print("한글 폰트 설정 완료!")
print("=" * 60)

============================================================
라이브러리 로드 완료!
한글 폰트 설정 완료!
============================================================

In [2]:
path = "/Users/wonwoo_mac/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/송원우/final_data/"

df = pd.read_csv(path + '젝시믹스_master.csv')
df.head()

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,helpful_count,has_image,purchase_option,purchase_option_color,purchase_option_size,women_size_yn,user_height,user_weight,user_height_group,user_weight_group,product_url,brand,cat1,cat2,cat3,gender,original_price,discount_price,color_count,is_new,is_best
0,2026-04-20,자사몰,5032253.0,2070608,UV 쉴드 에어핏 페이스 마스크,2026-03-09,2026,3,친구 소개로 구매했어요 친구가 걷기운동할때 필요해서 이것저것 구매했는데 기장 편하게...,5,1,1,색상:화이트 / 사이즈:L,화이트,L,0,158.0,50.0,155~159cm,50~54kg,https://www.xexymix.com/shop/shopdetail.html?b...,젝시믹스,용품,기타,골프,기타,19000.0,19000.0,3.0,False,True
1,2026-04-20,자사몰,4998316.0,2070608,UV 쉴드 에어핏 페이스 마스크,2026-01-26,2026,1,l사이즈 사고 원단도 좋고 운동시 호흡도 편한데 큰 느낌이라 작은사이즈 다시 주문했...,5,0,1,색상:블랙 / 사이즈:S/M,블랙,S/M,0,168.0,55.0,165~169cm,55~59kg,https://www.xexymix.com/shop/shopdetail.html?b...,젝시믹스,용품,기타,골프,기타,19000.0,19000.0,3.0,False,True
2,2026-04-20,자사몰,4936161.0,2070608,UV 쉴드 에어핏 페이스 마스크,2025-12-14,2025,12,구매하여 처음 사용해봤는데 가성비 진짜 좋네요 바람도 잘 막아주고 추운날씨에도 딱 ...,5,0,1,색상:블랙 / 사이즈:L,블랙,L,0,179.0,70.0,180~184cm,70~74kg,https://www.xexymix.com/shop/shopdetail.html?b...,젝시믹스,용품,기타,골프,기타,19000.0,19000.0,3.0,False,True
3,2026-04-20,자사몰,4727267.0,2070608,UV 쉴드 에어핏 페이스 마스크,2025-07-22,2025,7,전부터 풀페이스마스크 하나 사려고 보고 있다가 지난번 블랙색상 사고 마음에 들어서 ...,5,4,1,색상:화이트 / 사이즈:L,화이트,L,0,170.0,60.0,170~174cm,60~64kg,https://www.xexymix.com/shop/shopdetail.html?b...,젝시믹스,용품,기타,골프,기타,19000.0,19000.0,3.0,False,True
4,2026-04-20,자사몰,4821424.0,2070608,UV 쉴드 에어핏 페이스 마스크,2025-10-10,2025,10,낮에 러닝하는데 얼굴 타는게 신경쓰였는데 마스크 답답하지 않고 흘러 내리지 않아 좋아요,5,1,1,색상:화이트 / 사이즈:S/M,화이트,S/M,0,153.0,45.0,150~154cm,45~49kg,https://www.xexymix.com/shop/shopdetail.html?b...,젝시믹스,용품,기타,골프,기타,19000.0,19000.0,3.0,False,True

In [3]:
df_check = df[['review_id', 'review_date', 'product_name', 'year', 'month', 'rating', 'helpful_count', 'has_image', 'cat1', 'cat2', 'brand']].copy()
df_check.head()

,review_id,review_date,product_name,year,month,rating,helpful_count,has_image,cat1,cat2,brand
0,5032253.0,2026-03-09,UV 쉴드 에어핏 페이스 마스크,2026,3,5,1,1,용품,기타,젝시믹스
1,4998316.0,2026-01-26,UV 쉴드 에어핏 페이스 마스크,2026,1,5,0,1,용품,기타,젝시믹스
2,4936161.0,2025-12-14,UV 쉴드 에어핏 페이스 마스크,2025,12,5,0,1,용품,기타,젝시믹스
3,4727267.0,2025-07-22,UV 쉴드 에어핏 페이스 마스크,2025,7,5,4,1,용품,기타,젝시믹스
4,4821424.0,2025-10-10,UV 쉴드 에어핏 페이스 마스크,2025,10,5,1,1,용품,기타,젝시믹스

In [4]:
df_check.info()

<class 'pandas.DataFrame'>
RangeIndex: 501893 entries, 0 to 501892
Data columns (total 11 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   review_id      501893 non-null  float64
 1   review_date    501893 non-null  str
 2   product_name   501893 non-null  str
 3   year           501893 non-null  int64
 4   month          501893 non-null  int64
 5   rating         501893 non-null  int64
 6   helpful_count  501893 non-null  int64
 7   has_image      501893 non-null  int64
 8   cat1           501893 non-null  str
 9   cat2           501893 non-null  str
 10  brand          501893 non-null  str
dtypes: float64(1), int64(5), str(5)
memory usage: 81.7 MB

In [5]:
df_check[['brand', 'has_image']].head()

  brand  has_image
0  젝시믹스          1
1  젝시믹스          1
2  젝시믹스          1
3  젝시믹스          1
4  젝시믹스          1

### 모델링 추출 데이터셋 확인

In [7]:
df_bert = pd.read_parquet(path + 'dashboard_reviews_110M.parquet')
df_absa = pd.read_parquet(path + 'absa_phase_e_predictions.parquet')

In [8]:
df_absa.info()

<class 'pandas.DataFrame'>
RangeIndex: 12056 entries, 0 to 12055
Data columns (total 43 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   collect_date           12056 non-null  str
 1   platform               12056 non-null  str
 2   review_id              12056 non-null  float64
 3   product_id             12056 non-null  str
 4   product_name           12056 non-null  str
 5   review_date            12056 non-null  str
 6   year                   12056 non-null  int64
 7   month                  12056 non-null  int64
 8   content                12056 non-null  str
 9   rating                 12056 non-null  int64
 10  helpful_count          12056 non-null  int64
 11  has_image              12056 non-null  int64
 12  purchase_option        12056 non-null  str
 13  purchase_option_color  12056 non-null  str
 14  purchase_option_size   12056 non-null  str
 15  women_size_yn          12056 non-null  int64
 16  user_height            2934 non-null   float64
 17  user_weight            2894 non-null   float64
 18  user_height_group      12056 non-null  str
 19  user_weight_group      12056 non-null  str
 20  product_url            9042 non-null   str
 21  brand                  12056 non-null  str
 22  cat1                   12056 non-null  str
 23  cat2                   12056 non-null  str
 24  cat3                   12056 non-null  str
 25  gender                 12056 non-null  str
 26  original_price         12056 non-null  float64
 27  discount_price         12056 non-null  float64
 28  color_count            12056 non-null  float64
 29  is_new                 12056 non-null  str
 30  is_best                12056 non-null  str
 31  content_clean          12056 non-null  str
 32  content_len            12056 non-null  int64
 33  tokens                 12056 non-null  str
 34  tokens_topic           12056 non-null  str
 35  neg_aspects            12056 non-null  str
 36  pos_aspects            12056 non-null  str
 37  핏/사이즈                  12056 non-null  str
 38  소재/내구성                 12056 non-null  str
 39  기능성                    12056 non-null  str
 40  디자인                    12056 non-null  str
 41  브랜드/헤리티지               12056 non-null  str
 42  가격/가치                  12056 non-null  str
dtypes: float64(6), int64(7), str(30)
memory usage: 16.3 MB

In [9]:
df_absa.head()

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,helpful_count,has_image,purchase_option,purchase_option_color,purchase_option_size,women_size_yn,user_height,user_weight,user_height_group,user_weight_group,product_url,brand,cat1,cat2,cat3,gender,original_price,discount_price,color_count,is_new,is_best,content_clean,content_len,tokens,tokens_topic,neg_aspects,pos_aspects,핏/사이즈,소재/내구성,기능성,디자인,브랜드/헤리티지,가격/가치
0,2026-04-17,자사몰,361896950.0,prod20002583,저지 트레이닝 롱슬리브 셔츠 *워드마크,2025-10-14,2025,10,역시 편한한 데일리로 최고! 일단 원단이 저지원단이라 구김없고 편하고 소매도 시보리...,5,0,0,M,unknown,M,0,NaN,NaN,unknown,55-59kg,NaN,룰루레몬,상의,긴팔티셔츠,트레이닝,Women,93000.0,93000.0,2.0,False,False,역시 편한한 데일리로 최고 일단 원단이 저지원단이라 구김없고 편하고 소매도 시보리라...,77,편하다 데일리 최고 원단 저지 원단 구김 없다 편하다 소매 시보리 걷다 편하다 룰루...,편하다 데일리 최고 원단 저지 원단 구김 없다 편하다 소매 시보리 걷다 편하다 룰루...,,"디자인, 브랜드/헤리티지",P,P,P,P,P,X
1,2026-04-21,자사몰,36551446.0,10587,[1&1] 에어리핏 와이드 팬츠,2025-03-03,2025,3,기장수선안해도 되고 맞춤으로 잘맞아요..주름가지았고 편하고 두루두루 자주 입을것 같...,5,0,0,"사이즈=S (55), 색상=[ANPPT-20BLK] 숏 블랙, 사이즈=S (55),...","블랙,화이트머스크","S (55),S (55)",0,NaN,NaN,155~159cm,45~49kg,https://andar.co.kr/product/detail.html?produc...,안다르,세트상품,의류세트,일반,여성,138000.0,109000.0,10.0,False,False,기장수선안해도 되고 맞춤으로 잘맞아요 주름가지았고 편하고 두루두루 자주 입을것 같아...,54,기장 수선 맞춤 잘맞다 주름가지았 편하다 에어리핏 와이드 팬츠 편하다,기장 수선 맞춤 잘맞다 주름가지았 편하다 에어리핏 와이드 팬츠 편하다,,브랜드/헤리티지,P,X,P,X,P,X
2,2026-04-20,자사몰,4505095.0,2075483,블랙라벨 시그니처 파워라이즈 파이톤 배색 브라탑 살사레드,2025-03-22,2025,3,레깅스는 먼저 구매해서 예쁘게 편하게 입고 있는데 망설이다 다시 탑을 구매 해 봅니...,5,0,1,사이즈:M(55반~66) / 기본패드:에어브라패드,unknown,M(55반~66),0,162.0,45.0,160~164cm,45~49kg,https://www.xexymix.com/shop/shopdetail.html?b...,젝시믹스,상의,스포츠브라탑,일반,여성,49000.0,49000.0,2.0,False,False,레깅스는 먼저 구매해서 예쁘게 편하게 입고 있는데 망설이다 다시 탑을 구매 해 봅니...,81,레깅스 예쁘다 편하다 망설이다 편하다 재질 부드럽다 예쁘다 빨강 멋지다 예쁘다 너무...,레깅스 예쁘다 편하다 망설이다 편하다 재질 부드럽다 예쁘다 빨강 멋지다 예쁘다 좋다 블랙,,"소재/내구성, 디자인",P,P,P,P,X,X
3,2026-04-20,자사몰,4273711.0,2077455,[2PACK] 매직밴딩 맨즈 슬랙스 9.1&9.6,2024-10-26,2024,10,정말 활동하기 편한 바지입니다 색상도 마음에 들고 가볍고 따뜻합니다 밴딩이 있어서 ...,5,0,1,선택1:기모 9.6 라이트베이지 XL(+2000) / 선택2:기본 9.6 오이스터베...,"라이트베이지,오이스터베이지","XL,XL",0,177.0,80.0,175~179cm,80~84kg,https://www.xexymix.com/shop/shopdetail.html?b...,젝시믹스,세트상품,의류세트,골프,남성,158000.0,124800.0,9.0,False,True,정말 활동하기 편한 바지입니다 색상도 마음에 들고 가볍고 따뜻합니다 밴딩이 있어서 ...,67,정말 활동 편하다 바지 색상 마음에들다 가볍다 따뜻하다 밴딩 있다 작다 잘맞다 넓다...,활동 편하다 바지 색상 마음에들다 가볍다 따뜻하다 밴딩 있다 작다 잘맞다 넓다 라인 강추,,"핏/사이즈, 기능성, 브랜드/헤리티지",P,P,P,P,P,X
4,2026-04-28,자사몰,137521.0,8100359471140,판테라 99/25 LX,2026-02-04,2026,2,브라운 운동화는 처음인데 색상이 너무 맘에 들어요 너무 붉지도 너무 어둡지도 않는 ...,5,0,1,unknown,unknown,unknown,0,NaN,NaN,unknown,unknown,https://www.fila.co.kr/products/1100fs261ru03x...,FILA,신발,스니커즈,일반,여성,129000.0,129000.0,1.0,1.0,1.0,브라운 운동화는 처음인데 색상이 너무 맘에 들어요 너무 붉지도 너무 어둡지도 않는 ...,136,브라운 운동화 처음 색상 너무 마음에들다 너무 붉다 너무 어둡다 어울리다 고동색 가...,브라운 운동화 처음 색상 마음에들다 붉다 어둡다 어울리다 고동색 가깝다 갈색 좋다 ...,,디자인,P,X,P,P,X,X

In [10]:
df_bert.info()

<class 'pandas.DataFrame'>
RangeIndex: 1110129 entries, 0 to 1110128
Data columns (total 6 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   brand       1110129 non-null  str
 1   rating      1110129 non-null  int64
 2   topic       1110129 non-null  int64
 3   topic_name  1110129 non-null  str
 4   aspect      676951 non-null   str
 5   content     1110129 non-null  str
dtypes: int64(2), str(4)
memory usage: 312.5 MB

In [11]:
df_bert.head()

,brand,rating,topic,topic_name,aspect,content
0,안다르,5,28,"[기능성] 릴렉스마사지, 시원하다, 스틱",aspect_function,"러닝 후 몸 풀어주는 용으로 아주 좋아요. 종아리나 등, 목 뒤에 사용하기 좋아요...."
1,안다르,3,-1,[노이즈] 분류불가,NaN,딱딱하네요\n저는 말랑말랑 한줄 알았어요(2026-04-07 20:15:59 에 등...
2,안다르,5,-1,[노이즈] 분류불가,NaN,요가링이랑 폼롤러랑 같이 사서 집에서 잘 굴려주고 있어요 색깔도 너무 예쁘고 귀여워...
3,안다르,5,28,"[기능성] 릴렉스마사지, 시원하다, 스틱",aspect_function,묵직하니 사용하기 편하네요 릴렉스 마사지 듀얼볼 Ⅱ 후기 정사이즈
4,안다르,5,28,"[기능성] 릴렉스마사지, 시원하다, 스틱",aspect_function,시원하게 마사지가되요 여기저기 쉽게 문지르고 아픈 부위 꾹꾹 눌러주니 시원하네요 릴...